# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.1.0

compiler:
  solc:
    version: 0.8.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.0"